#pragma once
#include "colors.h"

#define RING_LED_COUNT 16
#define RING_DI_PIN 3
#define BUTTON_INPUT_PIN 4

// Lighting constants
#define DEFAULT_BRIGHTNESS 5

#define SKIPPED_COLOR GRAY
#define SKIPPED_MIN_BRIGHTNESS 10
#define SKIPPED_MAX_BRIGHTNESS 255
#define SKIPPED_PULSE_DURATION 6000  // milliseconds

#define MY_PLAYER_COLOR LIGHT_BLUE
#define OTHER_PLAYER_COLORS PINK
#define CURRENT_PLAYER_COLOR GREEN
#define CURRENT_PLAYER_PULSE_DURATION 6000  // milliseconds
#define CURRENT_PLAYER_MIN_BRIGHTNESS 10
#define CURRENT_PLAYER_MAX_BRIGHTNESS 255

#define AWAIT_GAME_START_SPEED 200
#define AWAIT_GAME_COLOR_1 GRAPE
#define AWAIT_GAME_COLOR_2 FOREST_GREEN
#define AWAIT_GAME_COLOR_3 CYAN
#define AWAIT_GAME_COLOR_4 PINK_BUBBLE_GUM