#pragma once
#include "colors.h"

#define LED_ADAFRUIT 0

#define RING_LED_COUNT 16
#define RING_DI_PIN 3
#define BUTTON_INPUT_PIN 4

// Lighting constants
#define DEFAULT_BRIGHTNESS 5

#define SKIPPED_COLOR GRAY
#define SKIPPED_MIN_BRIGHTNESS 0
#define SKIPPED_MAX_BRIGHTNESS 20
#define SKIPPED_PULSE_DURATION 4000  // milliseconds

#define MY_PLAYER_COLOR BLUE
#define OTHER_PLAYER_COLORS PINK
#define CURRENT_PLAYER_COLOR GREEN
#define CURRENT_PLAYER_PULSE_DURATION 4000  // milliseconds
#define CURRENT_PLAYER_MIN_BRIGHTNESS 5
#define CURRENT_PLAYER_MAX_BRIGHTNESS 20

#define AWAIT_GAME_START_SPEED 200
#define AWAIT_GAME_COLOR_1 YELLOW
#define AWAIT_GAME_COLOR_2 GREEN
#define AWAIT_GAME_COLOR_3 CYAN
#define AWAIT_GAME_COLOR_4 PURPLE

#define AWAIT_CONNECTION_SPEED 200
#define AWAIT_CONNECTION_COLOR BLUE
