#pragma once
#include "colors.h"

#define LED_ADAFRUIT 0

#define RING_LED_COUNT 16
#define RING_DI_PIN 3
#define BUTTON_INPUT_PIN D2

// Lighting constants
#define DEFAULT_BRIGHTNESS 5

#define SKIPPED_COLOR GRAY
#define SKIPPED_MIN_BRIGHTNESS 0
#define SKIPPED_MAX_BRIGHTNESS 20
#define SKIPPED_PULSE_DURATION 4000 // milliseconds

#define EXPAND_TURN_SEQUENCE_BUFFER 1
#define MY_PLAYER_COLOR BLUE
#define OTHER_PLAYER_COLORS PINK
#define CURRENT_PLAYER_COLOR GREEN
#define CURRENT_PLAYER_PULSE_DURATION 4000 // milliseconds
#define CURRENT_PLAYER_MIN_BRIGHTNESS 5
#define CURRENT_PLAYER_MAX_BRIGHTNESS 20

#define AWAIT_GAME_START_SPEED 200
#define AWAIT_GAME_COLOR1 GREEN
#define AWAIT_GAME_COLOR2 RED
#define AWAIT_GAME_COLOR3 BLUE
#define AWAIT_GAME_COLOR4 YELLOW
#define AWAIT_GAME_COLOR5 CYAN
#define AWAIT_GAME_COLOR6 PURPLE
#define AWAIT_GAME_COLOR7 ORANGE
#define AWAIT_GAME_COLOR8 WHITE
#define AWAIT_GAME_COLOR9 NAVY
#define AWAIT_GAME_COLOR10 MINT
#define AWAIT_GAME_COLOR11 PINK
#define AWAIT_GAME_COLOR12 MAROON
#define AWAIT_GAME_COLOR13 OLIVE
#define AWAIT_GAME_COLOR14 TEAL
#define AWAIT_GAME_COLOR15 BROWN
#define AWAIT_GAME_COLOR16 LILAC

#define AWAIT_CONNECTION_SPEED 200
#define AWAIT_CONNECTION_COLOR BLUE

#define GAME_PAUSED_SPEED 200
// Must divide evenly into the total LED count
#define GAME_PAUSED_SEGMENTS 2
#define GAME_PAUSED_APPLY_OFFSET 1
#define GAME_PAUSED_COLOR WHITE